# We're going to create a new pool for 198.19.24.0/21 that we want to be externally routable.
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: external-pool
spec:
  cidr: 198.19.24.0/21
  blockSize: 29
  ipipMode: Never
  natOutgoing: true
  nodeSelector: "!all()"

# calicoctl apply -f ./manifests/calico.ippools.yaml
